# 头部菜单，title: link
menu:
  首页: /
  分类: /categories
  标签: /tags
  归档: /archives
  关于: /about

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐（随机播放）
mp3:
    - http://link.hhtjim.com/163/425570952.mp3
    - http://link.hhtjim.com/163/425570952.mp3

# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)
welcome_cover: /img/cover/31.jpg

# 默认文章封面图（随机调用,支持外链）
cover:
  - /img/cover/1.jpg
  - /img/cover/2.jpg
  - /img/cover/3.jpg
  - /img/cover/4.jpg
  - /img/cover/5.jpg
  - /img/cover/6.jpg
  - /img/cover/7.jpg
  - /img/cover/8.jpg
  - /img/cover/9.jpg
  - /img/cover/10.jpg
  - /img/cover/11.jpg
  - /img/cover/12.jpg
  - /img/cover/13.jpg
  - /img/cover/14.jpg
  - /img/cover/15.jpg
  - /img/cover/16.jpg
  - /img/cover/17.jpg
  - /img/cover/18.jpg
  - /img/cover/19.jpg
  - /img/cover/20.jpg
  - /img/cover/21.jpg
  - /img/cover/22.jpg
  - /img/cover/23.jpg
  - /img/cover/24.jpg
  - /img/cover/25.jpg
  - /img/cover/26.jpg
  - /img/cover/27.jpg
  - /img/cover/28.jpg
  - /img/cover/29.jpg
  - /img/cover/30.jpg
  - /img/cover/31.jpg
  - /img/cover/32.jpg
  - /img/cover/33.jpg
  - /img/cover/34.jpg
  - /img/cover/35.jpg
  - /img/cover/36.jpg
  - /img/cover/37.jpg
  - /img/cover/38.jpg
  - /img/cover/39.jpg
  - /img/cover/40.jpg
  - /img/cover/41.jpg
  - /img/cover/42.jpg
  - /img/cover/43.jpg
  - /img/cover/44.jpg
  - /img/cover/45.jpg
  - /img/cover/46.jpg
  - /img/cover/47.jpg
  - /img/cover/48.jpg
  - /img/cover/49.jpg
  - /img/cover/50.jpg
  - /img/cover/51.jpg
  - /img/cover/52.jpg
  - /img/cover/53.jpg
  - /img/cover/54.jpg
  - /img/cover/55.jpg
  - /img/cover/56.jpg
  - /img/cover/57.jpg
  - /img/cover/58.jpg
  - /img/cover/59.jpg
  - /img/cover/60.jpg
  - /img/cover/61.jpg
  - /img/cover/62.jpg
  - /img/cover/63.jpg
  - /img/cover/64.jpg
  - /img/cover/65.jpg
  - /img/cover/66.jpg
  - /img/cover/67.jpg
  - /img/cover/68.jpg

# 是否显示Twitter分享卡片图像(图像尺寸要求：1200*600，creatorid不需要带@符号。注意：链接必须是完整url，否则Twitter将无法读取图片信息）
twitterpic:
  enable: false
  src: https://bangdream.moe/img/ident.png
  creatorid: yourtwitteridhere

# 是否使用mathjax
mathjax: false


# 是否关闭默认滚动条
scrollbar: true

# 本地搜索,请将索引文件放在网站根目录,或修改主题js文件的path值
local_search:
    # 是否启用
    enable: true
search:
  path: search.xml
  field: all
  format: html
  limit: 10000
# 是否显示 一言(hitokoto)
hitokoto: true

# 链接(可选:facebook,twitter,github,wechat,email)
links:
    facebook: /
    twitter: /
    github: https://github.com/Bioinformatics-rookie
    wechat: /img/erwei.jpg
    email: mailto:zhoushizhao@mai.kib.ac.cn

# 备案
beian:
    # 是否显示备案信息
    enable: true
    # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
    enableFooter: false
    # 备案号
  #  beianInfo: 冀ICP备xxxxxxx号
    # 链接地址
  #  link: http://www.beian.miit.gov.cn

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否启用评论功能
    enable: false
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: ''
    # 应用秘钥
    clientSecret: ''
    # issue仓库名
    repo: ''
    # Github名
    owner: ''
    # Github名
    admin: ['']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: zhoushizhao

deploy:
  type: git
  repo: https://gitee.com/zhou-sz/blog/
  branch: master


# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics:

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
